---
pull_request_rules:
  - name: automatic merge for pre-commit pull requests
    conditions:
      - author=pre-commit-ci[bot]
      - check-success=pre-commit.ci - pr
      - check-success=mergefreeze
    actions:
      merge:
        method: merge
